Face mood
hedita/react-mini-projects pull request #6
Opened 2023-02-05 19:15 UTC by hedita

2023-02-05 22:30 UTC, blacksrc requested changes

2023-02-05 22:30 UTC, blacksrc commented on src/FaceMood.jsx
> +          {person.name} is {person.mood}. :)
Please destructure name and mood in function argument.

2023-02-05 22:30 UTC, blacksrc commented on src/FaceMood.jsx
> +      return (
Do not repeat the return. Define a variable and name it emoji and fill it based on conditions. Then use that in the return once.

2023-02-06 18:41 UTC, hedita commented on src/FaceMood.jsx
> +          {person.name} is {person.mood}. :)
Done.

2023-02-07 11:37 UTC, hedita commented on src/FaceMood.jsx
> +      return (
Done.

2023-02-07 11:37 UTC, merged